blog/urls.py
from django.conf.urls import url
from .import views
from . import views
urlpatterns = [
    url(r'^index/$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.index,name='artice_page'),
    url(r'^edit/$', views.edit_page,name="edit_page"),
    url(r'^edit/action$', views.edit_action,name="edit_action"),
]

blog2/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^index/', views.index),
]

myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls',namespace='blog')),
    url(r'^blog2/',include('blog2.urls')),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Article(models.Model):
    title=models.CharField(max_length=32,default='Title')
    content=models.TextField(null=True)

    def __unicode__(self):
        return self.title

blog2/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import  render
from django.http import HttpResponse

from . import models
from django.shortcuts import render
from django.http import HttpResponse

from .import models

def index(request):
    articles =models.Article.objects.all()
    return render(request,'blog/index.html',{'articles': articles})

def article_page(request,article_id):
    article=models.Article.objects.get(pk=article_id)
    return render(request,'blog/article_page.html',{'article':article})

def edit_page(request):
    return render(request,'blog/edit_page.html')

def edit_action(request):
    title= request.POST.get('title','TITLE')
    content=request.POST.get('content','CONTENT')
    models.Article.objects.create(title=title,content=content)
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})

blog2/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse

from .import models

def index(request):
    articles =models.Aritle.objects.all()
    return render(request,'blog/index.html',{'articles': articles})

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article page</title>
</head>
<br>
<h1>{{article.title}}</h1>
</br>
<h3>{{article.content}}</h3>
</br></br>
<a href=''>修改文章</a>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
< lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit page</title>
</head>
<body>
<form action="{% url 'blog:edit_action'%}" method="post">
    {%  csrf_token %}
    <label>文章标题
        <input type="text" name="title">
    </label>
    </br>
    <label> 文章内容
        <input type="text" name="content">
    </label>
    </br>
    <input type="submit" value="提交">
</form>>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta char charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>
    <a href="">新文章</a>
</h1>
{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a>
    <br />
{% endfor %}
</body>
</html>

blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>fancy</title>
</head>
<body>
hello,blog2!
</body>
</html>